### ISSUE TITLE
ADD step copies local node_modules to the container

### ISSUE THREAD

**Issue by Guuz** [docker-library/node#23]
Hello,

As I have reported here:
https://github.com/GoogleCloudPlatform/nodejs-docker/issues/22
and here:
https://github.com/dockerfile/nodejs-runtime/issues/2

the local node_modules dir is copied over the correct one in the container. I'm thinking this might only be a problem when the .dockerignore file is not supported. This is the case on Google Managed VM's.
Could someone verifie it works as intended so we know it's only a problem for Managed VM's?

Thanks!

**Comment by yosifkit** [comment]
Closing old issue, (should be reported on https://github.com/nodejs/docker-node if you still have issues).
