### ISSUE TITLE
Support for npm-shrinkwrap.json

### ISSUE THREAD

**Issue by abesto** [docker-library/node#30]
I almost sent a trivial PR with `COPY npm-shrinkwrap.json /usr/src/app`, but the obvious problem is this breaks for projects without a shrinkwrap JSON. I don't (yet?) know how to fix this, so just opening an issue.

**Comment by abesto** [comment]
Sorry, wrong button.

Yes, adding it to the documentation would be nice.

**Comment by yosifkit** [comment]
Closing old issue, (should be reported on the new repo https://github.com/nodejs/docker-node if you still have issues).
